### ISSUE TITLE
Where to put base_url?

### ISSUE THREAD

**Issue by saintly2k** [evokelektrique/kawaii#1]
I have no idea how or where to put my base_url
![6E14C660-6A35-4F38-966B-9CFA6F641529](https://user-images.githubusercontent.com/63718132/128639571-d5645fd4-67ef-4b53-98ab-dd1030eec7c8.jpeg)
What do I have to replace? Or do I have to uncommon where I already wrote the full URL?

Also, I imported the database to one of my existing ones and changed the database.php file according to the new variables. However I still get an error.

**Comment by evokelektrique** [comment]
Hey there, well it's has an old code base actually it's based on Code Igniter 3 and it will automatically detects the base url unless you want a custom one you have to change this line to your desired base url

https://github.com/evokelektrique/kawaii/blob/c68cf78993d9d4114b16054f9cc09fe7e4888dc6/application/config/config.php#L30

Change it to something like:
```php
$config['base_url'] = "http://example.com";
```

And your second problem about database, could you provide more information about the errors you get?

**Comment by saintly2k** [comment]
Okay, I think the first problem is fixed, now the database one.
This is my database.php and everything should work
![11385618-E2AF-4A26-A4A4-D29E2A746149](https://user-images.githubusercontent.com/63718132/128911340-34608c27-40d5-4300-8890-ce9f27ae6d4a.jpeg)
However, it doesn’t.
I enabled error logs and checked them, this is what I get:
![0A1CB8EE-76FC-48A1-8460-C89290B9C458](https://user-images.githubusercontent.com/63718132/128911666-84d3f230-df7f-4fac-b6f7-f0b86d1940e3.jpeg)
Since I’m not very familiar with php and MySQL connections, I want to ask if you know how to fix this error?

edit: I checked the file given in the error logs, it seems fine to me (I’m not an expert/php guy though)

**Comment by evokelektrique** [comment]
Interesting, as you can see it's pointing it at the `mysql_connect()` function which seems MySQL module is not installed,
I found a quick solution [here on stackoverflow](https://stackoverflow.com/a/13825126) I hope it will solve your issue.

**Comment by saintly2k** [comment]
Hello, I fixed these errors by switching to php 5.6, now the last error I get is
ERROR - 2021-08-11 16:58:17 --> Unable to load the requested class: Jalalicalendar
Can I remove the class or is it necessary for it to run?

**Comment by evokelektrique** [comment]
![image](https://user-images.githubusercontent.com/53313989/129205583-2a45cf6e-386e-4fc4-ba08-acf0b2338bc4.png)

Weird I just cloned the repo and I configured it as it is described in the `README.md` and it worked well, I think there has to be a problem with your PHP because I didn't run into any problem and I'm using PHP Version 7.3.5

That class is actually used to convert gregorian calendar to jalali but you can see where it is been used [here](https://github.com/evokelektrique/kawaii/search?q=Jalalicalendar)

**Comment by saintly2k** [comment]
okay, i somehow managed to fix the problem and it works fine, but is there an english version of it available? since i want to create an english site...

**Comment by evokelektrique** [comment]
Nice!, 
Well I did not intend to translate into English, but it should be easy to translate the texts.
I mean we have Google Translate and et cetera

**Comment by saintly2k** [comment]
I'll fork it and try to give my best haha

**Comment by mafdy0samy** [comment]
> Hello, I fixed these errors by switching to php 5.6, now the last error I get is ERROR - 2021-08-11 16:58:17 --> Unable to load the requested class: Jalalicalendar Can I remove the class or is it necessary for it to run?

How did you fix the problem
